name: planckton-flow
channels:
  - conda-forge
dependencies:
  - gsd=2.2.0
  - python=3.7
  - pip=20.2
  - signac=1.6.0
  #- signac-flow=0.12.0
  - pip:
    - pytest
    - git+https://github.com/glotzerlab/signac-flow.git
