name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    container: 
        image: cmelab/planckton_cpu:0.1.5

    steps:
    - uses: actions/checkout@v2
 
    - name: Run pytest with coverage report
      run: conda run -n planckton python -m pytest
